site_name: Steppy
site_description: A tiny framework for composing small, type-safe Java steps into robust workflows
docs_dir: docs
site_dir: site

# Navigation structure
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Getting started: getting-started.md
  - Flows: flows.md
  - Branching & Nesting: branching.md
  - Streaming: streaming.md
  - State & Lifecycle: state.md
  - Configuration: configuration.md
  - Dependency injection: dependency-injection.md
  - Validation & Errors: validation.md

# Theme configuration - using a more standard setup
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono

# Repository information
repo_name: steppy
repo_url: https://github.com/habecker/steppy
edit_uri: edit/main/docs/

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

# Extra CSS and JS
extra_css:
  - style.css

# Site URL for GitHub Pages
site_url: https://habecker.github.io/steppy/
