hide circle

hide empty members
hide empty methods

skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false
skinparam noteBackgroundColor white
skinparam defaultFontName Times
'skinparam sequenceParticipant underline

skinparam class {
    fontStyle bold
    fontSize 14
    attributeFontSize 14
    stereotypeFontSize 14
}

skinparam sequence{
	LifeLineBorderColor gray
	LifeLineBackgroundColor white
    GroupBackgroundColor white
}

hide footbox