name: Release

on:
  push:
    tags:
      - 'v*'

env:
  MAVEN_OPTS: -Dfile.encoding=UTF-8

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup Maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "habecker",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set Maven version
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.VERSION }}

      - name: Build and deploy
        run: mvn --batch-mode clean deploy

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            target/*.jar
            target/*-sources.jar
            target/*-javadoc.jar
